remote_theme: pmarsceill/just-the-docs

color_scheme: dark

title: The Laboratory
description: A Collection 
url: "https://doctorzorka.github.io" 

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Maximum amount of previews per search result
 previews: 5